import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [userInput, setUserInput] = useState("");
  const [todoList, setTodoList] = useState([]);

  const handleChange = (e) => {
    e.preventDefault();
    setUserInput(e.target.value);
    console.log(userInput);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setTodoList([userInput, ...todoList]);
    setUserInput("");
  };

  const handleDelete = (todo) => {
    const updatedList = todoList.filter(
      (todoItem) => todoList.indexOf(todoItem) != todoList.indexOf(todo)
    );
    setTodoList(updatedList);
  };
  return (
    <div>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Todo List</h1>

        <div>
          <form>
            <input
              type="text"
              placeholder="Enter a todo item"
              value={userInput}
              onChange={handleChange}
            />
            <button onClick={handleSubmit}>Submit</button>
          </form>
        </div>

        <ul>
          {todoList.length >= 1
            ? todoList.map((todo, idx) => {
                return (
                  <li key={idx}>
                    {todo}{" "}
                    <button
                      onClick={(e) => {
                        e.preventDefault();
                        handleDelete(todo);
                      }}
                    >
                      Delete
                    </button>
                  </li>
                );
              })
            : `Enter a todo item`}
        </ul>
      </main>
    </div>
  );
}
